import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import "dotenv";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "@/providers/providers";

const karla = Open_Sans({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={karla.className} suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
